// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/I1Asyl/berliner_backend/pkg/handler"
	"github.com/I1Asyl/berliner_backend/pkg/repository"
	"github.com/I1Asyl/berliner_backend/pkg/services"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

// InitializeApp wires up all dependencies and returns the router
func InitializeApp(config Config) (*gin.Engine, error) {
	repository := ProvideRepository(config)
	services := ProvideServices(repository)
	handler := ProvideHandler(services)
	engine := ProvideRouter(handler)
	return engine, nil
}

// wire.go:

// Config holds the application configuration
type Config struct {
	DSN string
}

// ProvideRepository creates a new repository instance
func ProvideRepository(config Config) *repository.Repository {
	return repository.NewRepository(config.DSN)
}

// ProvideServices creates a new services instance
func ProvideServices(repo *repository.Repository) *services.Services {
	return services.NewService(repo)
}

// ProvideHandler creates a new handler instance
func ProvideHandler(services2 *services.Services) *handler.Handler {
	return handler.NewHandler(services2)
}

// ProvideRouter creates a new Gin router
func ProvideRouter(handler2 *handler.Handler) *gin.Engine {
	return handler2.InitRouter()
}
